# .gitlab-ci.yml

stages:
  - build
  - test
  - security
  - deploy

variables:
  DOCKER_REGISTRY: registry.example.com
  APP_NAME: transaction-service
  KUBE_NAMESPACE: banking-prod

# Build stage
build:
  stage: build
  image: maven:3.8-openjdk-17
  script:
    - echo "Building application..."
    - mvn clean package -DskipTests
    - echo "Build complete"
  artifacts:
    paths:
      - target/*.jar
    expire_in: 1 hour
  only:
    - merge_requests
    - main

# Unit test stage
unit-test:
  stage: test
  image: maven:3.8-openjdk-17
  script:
    - echo "Running unit tests..."
    - mvn test
    - echo "Generating coverage report..."
    - mvn jacoco:report
  coverage: '/Total.*?([0-9]{1,3})%/'
  artifacts:
    reports:
      junit: target/surefire-reports/TEST-*.xml
      coverage_report:
        coverage_format: cobertura
        path: target/site/jacoco/jacoco.xml
  only:
    - merge_requests
    - main

# Integration test stage
integration-test:
  stage: test
  image: maven:3.8-openjdk-17
  services:
    - postgres:14
    - redis:7
  variables:
    POSTGRES_DB: testdb
    POSTGRES_USER: testuser
    POSTGRES_PASSWORD: testpass
  script:
    - echo "Running integration tests..."
    - mvn verify -Pintegration-tests
  artifacts:
    reports:
      junit: target/failsafe-reports/TEST-*.xml
  only:
    - merge_requests
    - main

# Security scanning
security-scan:
  stage: security
  image: aquasec/trivy:latest
  script:
    - echo "Scanning for vulnerabilities..."
    - trivy fs --exit-code 0 --severity HIGH,CRITICAL .
    - trivy image --exit-code 0 $DOCKER_REGISTRY/$APP_NAME:$CI_COMMIT_SHA
  allow_failure: true
  only:
    - merge_requests
    - main

# SAST (Static Application Security Testing)
sast:
  stage: security
  image: returntocorp/semgrep:latest
  script:
    - semgrep --config=auto --json --output=sast-report.json .
  artifacts:
    reports:
      sast: sast-report.json
  allow_failure: true
  only:
    - merge_requests
    - main

# Build and push Docker image
docker-build:
  stage: build
  image: docker:24
  services:
    - docker:24-dind
  script:
    - echo "Building Docker image..."
    - docker build -t $DOCKER_REGISTRY/$APP_NAME:$CI_COMMIT_SHA .
    - docker tag $DOCKER_REGISTRY/$APP_NAME:$CI_COMMIT_SHA $DOCKER_REGISTRY/$APP_NAME:latest
    - echo "Pushing to registry..."
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $DOCKER_REGISTRY
    - docker push $DOCKER_REGISTRY/$APP_NAME:$CI_COMMIT_SHA
    - docker push $DOCKER_REGISTRY/$APP_NAME:latest
  only:
    - main

# Deploy to staging (ArgoCD)
deploy-staging:
  stage: deploy
  image: alpine:latest
  before_script:
    - apk add --no-cache git curl
  script:
    - echo "Updating ArgoCD manifests for staging..."
    - git clone https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.example.com/infra/argocd-manifests.git
    - cd argocd-manifests/apps/$APP_NAME/overlays/staging
    - sed -i "s|image:.*|image: $DOCKER_REGISTRY/$APP_NAME:$CI_COMMIT_SHA|g" kustomization.yaml
    - git config user.email "ci@example.com"
    - git config user.name "GitLab CI"
    - git add .
    - git commit -m "Update $APP_NAME to $CI_COMMIT_SHA [skip ci]"
    - git push origin main
    - echo "ArgoCD will sync automatically or trigger manual sync"
  environment:
    name: staging
    url: https://staging.example.com
  only:
    - main

# Deploy to production (ArgoCD) - manual trigger
deploy-production:
  stage: deploy
  image: alpine:latest
  before_script:
    - apk add --no-cache git curl
  script:
    - echo "Updating ArgoCD manifests for production..."
    - git clone https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.example.com/infra/argocd-manifests.git
    - cd argocd-manifests/apps/$APP_NAME/overlays/production
    - sed -i "s|image:.*|image: $DOCKER_REGISTRY/$APP_NAME:$CI_COMMIT_SHA|g" kustomization.yaml
    - git config user.email "ci@example.com"
    - git config user.name "GitLab CI"
    - git add .
    - git commit -m "Update $APP_NAME to $CI_COMMIT_SHA [skip ci]"
    - git push origin main
    - echo "ArgoCD will sync - monitor in ArgoCD UI"
  environment:
    name: production
    url: https://api.example.com
  when: manual
  only:
    - main

# AI-assisted pipeline optimization notes:
# - Agent suggested adding coverage reporting
# - Agent recommended Trivy for container scanning
# - Agent proposed parallel test execution (not yet implemented)

